---
title: "Data Tidying"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
```

## load package
```{r}
library(tidyverse) 
library(readxl)
```


## Problem 1
### Load/Clean Data
```{r}
nyc_mta = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", 
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
  janitor::clean_names() %>%
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
  rename(ADA_compliance = ada)%>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))

```

These data are not "tidy" as they now stand; route number and route should both be variables. That is, we would need to change "route" variables from wide to long format in order to have a clean dataset. 
### Answer Questions
```{r}
nyc_mta %>% 
  select(station_name, line) %>% 
  distinct

nyc_mta %>% 
  filter(ADA_compliance == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

There are 465 distinct stations, and 84 of them are ADA compliant.

```{r}
nyc_mta %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

```{r}
nyc_mta %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct

nyc_mta %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ADA_compliance == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

## Problem 2
### Load/Clean Data

```{r}
mr_trash_wheel = 
  readxl::read_excel("./data/Trash Wheel Collection Data.xlsx",
             sheet = "Mr. Trash Wheel", range = "A2:N550") %>%
    janitor::clean_names() %>%
  filter(dumpster >= 1) %>% 
  mutate(sports_balls = as.integer(sports_balls)) %>%
  mutate(trash_wheel_source = "Mr.")

mr_trash_wheel
```

```{r}
pro_trash_wheel = 
  readxl::read_excel("./data/Trash Wheel Collection Data.xlsx",
             sheet = "Professor Trash Wheel", range = "A2:M97") %>%
    janitor::clean_names() %>%
  filter(dumpster >= 1) %>%
  mutate(trash_wheel_source = "Professor") %>% 
  mutate(year = as.character(year))

pro_trash_wheel
```

### Join Two Dataset
```{r}
trash_wheel_data = 
  full_join(mr_trash_wheel, pro_trash_wheel, by  = c('dumpster','month','year','date','weight_tons','volume_cubic_yards','plastic_bottles','polystyrene','cigarette_butts','glass_bottles', 'grocery_bags', 'chip_bags', 'homes_powered', 'trash_wheel_source'))

trash_wheel_data

```


